#!/Users/borior/code/venv/sci/bin/python

import os
import sys
import matplotlib.pyplot as plt

data = [float(line) for line in sys.stdin]

plt.plot(data)

if os.isatty(sys.stdout.fileno()):
    plt.show()
else:
    plt.savefig(sys.stdout, format='png')
