#!/Users/borior/code/venv/sci/bin/python

import os
import sys
import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt(sys.stdin, unpack=True)
x = np.arange(len(data[0]))

for i, d in enumerate(data):
    plt.plot(x, d, label="col %d" % i)

plt.legend()

if os.isatty(sys.stdout.fileno()):
    plt.show()
else:
    plt.savefig(sys.stdout, format='png')
