#!/Users/borior/code/venv/sci/bin/python

from __future__ import print_function, division

import time
import sys

WIDTH = 80

def follow(f):
    while True:
        line = f.readline()
        if not line:
            time.sleep(1)
            continue
        yield line

def main():
    _, total, filename = sys.argv

    total = int(total)

    sys.stdout.write("[%s]" % (" " * WIDTH))
    sys.stdout.flush()
    sys.stdout.write("\b" * (WIDTH + 1))

    for i, line in enumerate(follow(open(filename)), start=1):
        num_ind = int(i * WIDTH / total)
        sys.stdout.write("=" * num_ind)
        sys.stdout.write(" " * (WIDTH - num_ind))
        sys.stdout.flush()
        sys.stdout.write("\b" * WIDTH)

if __name__ == '__main__':
    main()


